# Generated by Django 4.1.4 on 2022-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_product_options_product_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/products/"
            ),
        ),
    ]
