services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: DOCKERFILE
    expose:
      - 8000
    volumes:
      - ./web:/usr/src/app
    networks: 
      - backend
    command: gunicorn ilara.wsgi:application -w 2 -b :8000
  
  proxy:
    restart: always
    build:
      context: ./proxy
      dockerfile: dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks: 
      - backend

networks: 
  backend:
