# Generated by Django 4.1.4 on 2022-12-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
    ]
